[bot]
name = "DisSkele"                       # Your bot name
status = "online"                       # The status of the bot; online, idle, etc...
activity = "DisSkele - A d.py skeleton" # The activity message
prefix = ".ds"                          # Not used but required by discord.py

[ids]
sudo_users = [
    1027380375028244551, # roc.py
]
home_guild = 1212198952649363487 # Roc(k) - used for errors and emojis

[colors]
primary = 0xFFFFFF   # Used as the primary embed color
secondary = 0x868686 # Used for embed separation
invisible = 0x2B2D31 # Invisible embed color (dark mode only)
success = 0x00D355   # Used on command success
error = 0xDF0043     # Used on command errors

[emojis]
arrow_right = "<:arrow_right:1260800557355110453>"
chat = "<:chat:1260799727478247456>"
dns = "<:dns:1260799724013879346>"
false = "<:false:1260799722273116160>"
ping = "<:ping:1260799720960557149>"
trend_up = "<:trend_up:1260799728673882203>"
true = "<:true:1260799725989396591>"
